/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviebooking;

import javax.swing.JFrame;

/**
 *
 * @author jenie
 */
public class Homepage11 extends javax.swing.JFrame {

    /**
     * Creates new form Homepage11
     */
    public Homepage11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("HanziPen TC", 0, 24)); // NOI18N
        jLabel1.setText("Upcoming Movies");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("HanziPen TC", 3, 24)); // NOI18N
        jLabel2.setText("Hit Movies");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/皮卡丘.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 238, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/333.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 200, 300));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/前任.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 190, 290));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/哥斯拉.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 80, 190, 290));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/反贪.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 220, 300));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ti a.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 200, 300));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/he.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 190, 300));

        jButton2.setText("book now");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        jButton3.setText("book now");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        jButton4.setText("book now");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, -1, -1));

        jButton5.setText("book now");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 370, -1, -1));

        jButton6.setText("book now");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 720, -1, -1));

        jButton7.setText("book now");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 720, -1, -1));

        jButton8.setText("book now");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 720, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviebooking/zha.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 420, 190, 300));

        jButton9.setText("book now");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 720, -1, -1));

        jButton10.setBackground(new java.awt.Color(255, 51, 204));
        jButton10.setFont(new java.awt.Font("Wawati TC", 0, 18)); // NOI18N
        jButton10.setText("next>>");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, 220, -1));

        jButton11.setBackground(new java.awt.Color(255, 0, 153));
        jButton11.setFont(new java.awt.Font("Wawati TC", 0, 18)); // NOI18N
        jButton11.setText("Go to book private rooms");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/漫威.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1860, 1860, 1860))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1289, 1289, 1289))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        Homepage22 h2 = new Homepage22();
        h2.show();

    }//GEN-LAST:event_jButton10MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        pika a = new pika("POKÉMON名偵探皮卡丘", "Pokémon Detective Pikachu", "Rob Reitman", 7.4);
        a.setVisible(true);

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Book1 a = new Book1("Pikachu");
        a.setLocationRelativeTo(null);
        a.setVisible(true);

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Book1 a = new Book1("Captain America");
        a.setLocationRelativeTo(null);
        a.setVisible(true);

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        Book1 a = new Book1("Always miss you");
        a.setLocationRelativeTo(null);
        a.setVisible(true);

    }//GEN-LAST:event_jButton4MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Upcoming h1 = new Upcoming();
        h1.setLocationRelativeTo(null);
        h1.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        Book1 a = new Book1("Godzilla:King of the Monsters");
        a.setLocationRelativeTo(null);
        a.setVisible(rootPaneCheckingEnabled);

    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        Book1 a = new Book1("Tuner");
        a.setLocationRelativeTo(null);
        a.setVisible(true);

    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        Book1 a = new Book1("where is home");
        a.setLocationRelativeTo(null);
        a.setVisible(true);

    }//GEN-LAST:event_jButton7MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        pika2 a = new pika2("复仇者联盟4：终局之战", "Avengers:Endgame", "2019/04/24", 180, 9.3, "98%", "Director:Joe Russo",
                "Actors:Bradley Cooper, Brie Larson, Scarlett Johansson, Joe Henson, Karen Gillian",
                "<html><body>How does the world go on after ash flies smoke to destroy, whether to still have the opportunity that turns round ending?<br>"
                + " All will be revealed here. \"The avengers: the end game\" will be marvel's longest film ever, with a rich, compact, <br>"
                + "interconnected plot that happens almost every 10 minutes. The plot continues with \"avengers: infinity war,\"<br>"
                + " in which thanos destroys half the creatures in the universe at his fingers' length. Both hawkeye and ant-man, who weren't <br>"
                + "seen in avengers: infinity war, are in the film, and the public will use the quantum realm to return to the past......</body></html>"
        );
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        pika2 a = new pika2("下一任：前任", "Always Miss You", "2019/05/01", 90, 4.3, "33%", "Director:Hongyi Chen",
                "Actors:Guo Caijie, Zheng Kai, Li dongxue, Xie Yilin, Liu Xinyou, Qiu Xinyi, Li Ronghao",
                "<html><body>Lin xintian is dark love huang kequn for a long time, after growing up two people miss countless times, encounter<br>"
                + " a few predestined love less than again, think this lifetime won't goodbye. In the end, with their efforts and persistence, <br>"
                + "they came together......</body></html>");
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:

        Book1 a = new Book1("反贪风暴");
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        pika2 a = new pika2("调音师", "AndhaDhun", "2019/04/03", 139, 9.1, "92%", "Director:Sriram Raghavan",
                "Actors:Ayusman Khurana, Tabu, Radhika Apte, Anr Dehawan",
                "<html><body>A pretend blind pianist akash (ayoob, weissman khurana, act the role ofing), accidentally broke into the sex <br>"
                + "scene and saw thehostess sago (Mr) and his lover, Nora (manassas, va) clean up the male host Mr Plummer (anil into) body,<br>"
                + " left the crime scene after akash, between the \"blind\" and \"blind\", but I didn't think snake housewife sago and her<br>"
                + " lover already ahead. Sago worked to akash restaurant, in front of akash and restaurant owners has played a \"husband stood<br>"
                + " me up on their wedding anniversary, but also directly to akash home, tolerates his temptation, screaming masks, poison,<br>"
                + " face to face even pulled a gun directly......</body><html>");
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        pika2 a = new pika2("何以为家", "Where is home", "2019/04/29", 123, 9.3, "94%", "Director:Nadine Labaki",
                "Actors:Zane Al Lafayette,Jordanos Cifelo,Boruavatif Trej Bancor",
                "<html><body>In court, twelve-year-old zane sued his biological parents for giving him life. What kind of experience led a child to make such an incredible<br>"
                + " move? In the story, zane's parents keep giving birth despite their inability to raise and educate them. As the eldest son in the family,<br>"
                + " zane bears the heavy burden of life with his weak shoulders. When his sister is forcibly sold to a peddler as a wife, zane runs away from<br>"
                + " home in anger, and then meets a mother and son who have no legal status and support each other to make a living. However, life did not <br>"
                + "favor zane, and the hardships forced him to make a shocking move...</body></html>");
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);

    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        pika2 a = new pika2("反贪风暴4", "P Storm", "2019/04/04", 100, 9.1, "67%", "Director:DeLu Lin",
                "Actors:Louis Koo,Cheng Jiaying,Lin Feng,Lin Jiadong,Zhou Xiuna,Zhang Zhilin",
                "<html><body>Icac received the informant liao yuping (zhou xiuna) real name report, report is in prison rich second generation<br> "
                + "Cao Yuanyuan (Lin feng) suspected of bribery prison supervision shen jiquan (tan yaowen) and punishment teacher,<br>"
                + " chief investigation director lu zhilian (Louis koo) decided to go deep into the tiger's den, undercover prison.<br>"
                + " In the jail, the former superintendent huang wenbin that is sent into the jail by lu zhilian (Lin jiadong is acted <br>"
                + "the role of) and cao yuanyuan two big gang potential become fire and water, lu zhilian takes the opportunity to<br>"
                + " approach cao yuanyuan to gain trust......</body></html>");
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        pika2 a = new pika2("哥斯拉2：怪兽之王", "Godzilla: King of the Monsters", "2019/05/30", 112, 8.6, "84%", "Director:Alex Garcia",
                "Actors:Kyle Chandler, Millie Bobby Brown, Bradley Whitford, Vera Famega, Ken Watanabe, Sally Hawkins",
                "<html><body>The emperor project mystery government will continue to research and contact more monsters, including godzilla, laton,<br>"
                + " mothra, and the king of kidora! In particular, godzilla will face off against his ultimate enemy, the tri-headed king of beasts,<br>"
                + " guido! When these mythical giants rise again, they will once again play the role of king, and the fate of mankind <br>"
                + "is in their hands</body></html>");
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        Book1 a;
        a = new Book1("The Hustle");
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        pika2 a = new pika2("詐騙女神", "The Hustle(2019)", "2019/05/09", 94, 5, "43%", "Director:Chris Addison",
                "Actors: Anne hathaway,Rebel Wilson, Alex Sharp, Sarah Stephanie, Deepak Anand, Meena Rayann",
                "<html><body> A new female version of the 1988 comedy \"how to fool people\" starring Michael kown and Steve Martin will also guest star in <br>"
                + "the stage version. Film description of two female cheats, to cheat gold bad man, take men heart. The comedy follows Anne hathaway <br>"
                + "and rebel Wilson as a con-woman and a millionaire hooker who hook up with bad guys from around the world. Rebel Wilson and<br>"
                + " Anne hathaway are a pair of stunning fraudsters who set out to outfox each other in a seaside town in<br> "
                + "southern France.</body></html>");
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        search s;
        s = new search();
        s.setLocationRelativeTo(null);
        s.setVisible(true);
    }//GEN-LAST:event_jButton11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Homepage11().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
