/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package moviebooking;

import javax.swing.JFrame;

/**
 *
 * @author jenie
 */
public class Homepage22 extends javax.swing.JFrame {

    /** Creates new form Homepage22 */
    public Homepage22() {
        initComponents();
    }

    /** This method is called from within th
     * e constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("HanziPen TC", 3, 24)); // NOI18N
        jLabel2.setText("Hit Movies");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("HanziPen TC", 0, 24)); // NOI18N
        jLabel1.setText("Upcoming Movies");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/海.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 210, 310));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/港珠澳.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 210, 310));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/A02E7CAA-E93A-4F01-A11D-B016BC5A117B.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 200, 310));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/2499790F-CF87-4B70-8BEC-1175D2799073.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 430, 200, 310));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/进.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 210, 310));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ABFAB4BF-07B3-435C-881B-79EA86BA966E.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 210, 310));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/地久.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 200, 310));

        jButton3.setText("book now");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 400, -1, -1));

        jButton4.setText("book now");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, -1, -1));

        jButton5.setText("book now");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        jButton6.setText("book now");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 740, -1, -1));

        jButton7.setText("book now");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 740, -1, -1));

        jButton8.setText("book now");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 740, -1, -1));

        jButton9.setText("book now");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        jButton10.setFont(new java.awt.Font("Wawati TC", 0, 18)); // NOI18N
        jButton10.setText("back<<");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/五月天.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, 200, 300));

        jButton1.setText("book now");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 740, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/漫威.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, -30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 874, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        Homepage11 h1=new Homepage11();
        h1.setLocationRelativeTo(null);
        h1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Upcoming h1=new Upcoming();
        h1.setLocationRelativeTo(null);
        h1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        Book1 a =new Book1("Heidi");
        a.setLocationRelativeTo(null);
        a.setVisible(true);
       
    }//GEN-LAST:event_jButton5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Heidi h=new Heidi();
        h.setVisible(true);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        Book1 a=new Book1("HZM Bridge");
        a.setLocationRelativeTo(null);
        a.setVisible(true);
      
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
         Book1 a=new Book1("Roma");
        a.setLocationRelativeTo(null);
        a.setVisible(true);
      
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
         Book1 a=new Book1("Enter the Forbiden City");
        a.setLocationRelativeTo(null);
        a.setVisible(true);
       
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
         Book1 a=new Book1("Savage");
        a.setLocationRelativeTo(null);
        a.setVisible(true);
       
    }//GEN-LAST:event_jButton7MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         pika2 a=new pika2("港珠澳大桥","HZM Bridge","2019/05/01",70,9.3,"92%","Director:Dong Yan",
                " ",
                "<html><body>In this film, the installation process of E30 immersed tube in the last section of the construction of <br>"
                        + "hong kong-zhuhai-macao bridge is the main line of narration, showing the Chinese bridge Liang builders self-reliance,<br>"
                        + " \"pioneer spirit of innovation and arduous struggle, shows the bridge project involves hydrology, geology, white <br>"
                        + "dolphins, typhoon and satisfy the navigation, maritime, aviation limit higher for the construction of the complex <br>"
                        + "problem, and the bridge main body engineering bridge, the island, the three most tunnel design idea and the key <br>"
                        + "technology of the world's leading, like a kaleidoscope.......</body></html>"
               );       
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        pika2 a=new pika2("罗马","Roma","2019/05/10",135,9.1,"92%","Director:Alfonso Cuarón",
                "Actors:Yariza Barrisio, Marina De Tavila",
                "<html><body>Cleo is a native Mexican girl who works as a nanny for Sophia's family. Sophia has four children whose father, <br>"
                        + "Antonio, is spending less and less time at home. On the surface, the Sophia family lived a very happy life -- a beautiful<br>"
                        + " house and a good income. But cracks have appeared. Antonio is planning to leave his family under the pretext of work. Cleo<br>"
                        + " also had her problems, becoming pregnant after a less-than-pleasant date with Fermin. When she told Fermin the news, he<br> "
                        + "disappeared immediately.......</body></html>"
               );       
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Book1 a=new Book1("Mayday Life");
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
           pika2 a=new pika2("进京城","Enter the Forbidden City","2019/05/10",113,9.1,"92%","Director:Alfonso Cuarón",
                "Actors:Fu Dalong, Ma Yili, Ma Jinghan, Wang Ziwen, Jiao huang, Yao Anlian",
                "<html><body>Promising talent wusheng actor wang changsheng is yangzhou spring taiban star of hope.In the qianlong emperor sent chicken under<br>"
                        + " the jiangnan select opera into Beijing, wang changsheng is quite favored by the grid, but determined and his fiancee fang <br>"
                        + "chunrong agreed to elope. This move let spring taiban into a huge crisis, also let spring taiban owner jiang chun xiejin, lying sick<br>"
                        + " bed. On the other side, the name moves the famous son yue nine of capital city, however because the same trade designs frame and be driven<br>"
                        + " out of capital by the imperial court, be forced south to escape .......</body></html>"
               );       
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         pika2 a=new pika2("雪暴","Savage","2019/04/30",111,7.4,"67%","Director:Siwei Cui",
                "Actors:Zhang Zhen, Ni Ni, Liao Fan, Huang Jue, Li Guangjie",
                "<html><body>In a remote border town in the far north, a gang of gangsters do everything they can to rob gold. To give the avenge of sacrifice<br>"
                        + " comite in arms, police wang kanghao (zhang zhen is acted the role of) collect evidence secretly, be familiar with terrain, be in finally<br>"
                        + " when the blizzard of a disaster level comes, with the bandit of murder for money produced the front of breathtaking<br>"
                        + " and exciting duel.......</body></html>"
               );       
   
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
         pika2 a=new pika2("地久天长"," So Long My Son","2019/03/22",175,8.6,"87%","Director:Xiaoshuai Wang",
                "Actors:Wang Jingchun, Yong Mei, Qi Xi, Wang Yuan, Du Jiang, Ai La, Xu Cheng",
                "<html><body>Young liu yaojun and shen yingming two families were friends, often dance together playing CARDS, two children liu xing and shen<br>"
                        + " hao was born and grew up together, but in the suburbs play, yao jun's son liu xing died unexpectedly, this matter completely <br>"
                        + "changed the fate of the two families. Liu and his wife left their hometown to hide in a fishing village in fujian province. Shenyang husband<br>"
                        + " and wife official career is accomplished, because the accident in those days has another secret feeling however, the life did not get<br>"
                        + " quiet all the time. Years later, they meet again, the old face, the hidden truth will eventually come out........</body></html>"
               ); 
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        Book1 a=new Book1("So long My son");
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
          pika2 a=new pika2("五月天人生无限公司","Mayday Life","2019/05/24",112,7.1,"54%","Director:Yiren Chen",
                "Actors:五月天阿信、怪兽、石头、玛莎、冠佑",
                "<html><body>What is the experience of a movie with more than 4 million actors? Life unlimited, everyone who participated in <br>"
                        + "the lead. Every \"overtime night\" is so unforgettable, inside and outside the concert, your life story can have<br>"
                        + " what change and invariable? Mayday \"life unlimited company\" tour, spanning four continents, lasted a year and a <br>"
                        + "half, hundreds of Tours, more than 4 million viewers, constantly breaking records, constantly creating new moved........</body></html>"
               );       
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
            pika2 a;
        a = new pika2("樂獄","Bad Boy Symphony","2019/05/17",94,0,"0%","Director:Qiming Sun",
                "Actors:林哲熹 ，紀言愷 ，范少勳 ，金士傑 ，包小松 ，宋少卿",
                " different life background and enter the new juvenile prison second hospital. Starring the new generation of tomorrow stars<br>"
                        + "<html><body>Bad Boy Symphony is adapted from Taiwan real life facts, the story describes a group of youth is strong young, each have<br>"
                        + " Lin zhexi, JR ji yankai, fan shaoxun, cheng yuanyuan, ouyang lun, liu guoshao, qiu junru, kang xiang, Chen haosen, lian kai, xi<br>"
                        + " jingyan. In particular, we will invite veteran performers like jin shijie, xiao qiang, song shaoqing and bao xiaosong to <br>"
                        + "perform. Juvenile prison new two courtyard, a juvenile delinquent lei yuwei who has repeatedly failed to escape from prison, to <br>"
                        + "join the classical music ensemble, know when the whole world to give up you, only you can not give up their own, strive for early<br>"
                        + " parole out of prison. But found that the band members do not even know the staff, and often fight........</body></html>"
        );       
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Book1 a=new Book1("Bad BoySymphony");
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage22().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
