/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviebooking;

import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;


/**
 *
 * @author jenie
 */
public class insert extends javax.swing.JFrame {
        JFrame jf,jf2;
        JPanel jp,jp2;
        JLabel l1,l2;
    /**
     * Creates new form insert
     */
    public insert() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        U1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        C1 = new javax.swing.JTextField();
        E1 = new javax.swing.JTextField();
        P1 = new javax.swing.JPasswordField();
        Pa1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Pp1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Register");

        jLabel3.setText("UserName:");

        U1.setForeground(new java.awt.Color(102, 102, 102));
        U1.setText("ID");

        jLabel4.setText("Contact:");

        jLabel5.setText("Email:");

        jLabel6.setText("Password:");

        jLabel7.setText("Password again:");

        C1.setForeground(new java.awt.Color(102, 102, 102));
        C1.setText("Phone number");
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });

        E1.setForeground(new java.awt.Color(102, 102, 102));
        E1.setText("name@msn.com");

        P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jButton1.setText("Get back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 204));
        jButton2.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Paypassword:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Pa1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                            .addComponent(C1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(U1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pp1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(342, 342, 342)
                        .addComponent(jButton2)))
                .addContainerGap(1034, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(U1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Pa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Pp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(535, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/insert.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1ActionPerformed

    private void P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            try {
                String str="INSERT INTO bookinguser(UserName,mpnumber,Email,Userpw1,Paypw1)VALUES (?,?,?,?,?)";
                Connection con;
                PreparedStatement ps;
                String sql="select *from bookinguser where UserName=?";
                PreparedStatement pt;
                con=DB.getConnection();
                pt=con.prepareStatement(sql);
                pt.setString(1,U1.getText());
                ResultSet rs=pt.executeQuery();
                if(rs.next()){
                       jf=new JFrame("INSERT RESULT");
                            jp=new JPanel();
                            l1=new JLabel("The Username already exists");
                            jf.add(jp);
                            jp.add(l1);
                            jf.pack();
                            jf.setSize(400, 100);
                            jf.setLocationRelativeTo(null);
                            jf.setVisible(true);                           
                            return;
                }
                String st,regex;
                Pattern pattern;
                Matcher matcher;
                st=C1.getText();
                regex="^[0-9]{11}$";
                pattern=Pattern.compile(regex);
                matcher=pattern.matcher(st);
                if(!matcher.matches()){
                  jf=new JFrame("INSERT RESULT");
                            jp=new JPanel();
                            l1=new JLabel("Please enter the 11-digit number as required");
                            jf.add(jp);
                            jp.add(l1);
                            jf.pack();
                            jf.setSize(400, 100);
                            jf.setLocationRelativeTo(null);
                            jf.setVisible(true);                           
                            return;  
                }
                
                    String ui,regex1;
                    Pattern pattern1;
                    Matcher matcher1;
                    ui=E1.getText();
                    regex1="[a-zA-Z_]{0,}[0-9]{0,}@(([a-zA-z0-9]-*){1,}\\.){1,3}[a-zA-z\\-]{1,}";
                    pattern1=Pattern.compile(regex1);
                    matcher1=pattern1.matcher(ui);
                    if(!matcher1.matches()){
                    jf=new JFrame("INSERT RESULT");
                            jp=new JPanel();
                            l1=new JLabel("Please enter an correct e-mail!");
                            jf.add(jp);
                            jp.add(l1);
                            jf.pack();
                            jf.setSize(400, 100);
                            jf.setLocationRelativeTo(null);
                            jf.setVisible(true);                           
                            return;  
                    }
                    String uu,regex2;
                    Pattern pattern2;
                    Matcher matcher2;
                    uu=P1.getText();
                    regex2="[a-zA-Z0-9]{0,12}";
                    pattern2=Pattern.compile(regex2);
                    matcher2=pattern2.matcher(uu);
                    if(!matcher2.matches()){
                    jf=new JFrame("INSERT RESULT");
                            jp=new JPanel();
                            l1=new JLabel("Password cannot be longer than 12 characters!");
                            jf.add(jp);
                            jp.add(l1);
                            jf.pack();
                            jf.setSize(400, 100);
                            jf.setLocationRelativeTo(null);
                            jf.setVisible(true);                           
                            return;  
                    }
                if(P1.getText().equals(Pa1.getText())){
                    try {
                        
                        ps = con.prepareStatement(str);
                        ps.setString(1,U1.getText());
                        ps.setString(2,C1.getText());
                        ps.setString(3,E1.getText());
                        ps.setString(4,P1.getText());
                       
                        ps.setString(5, Pp1.getText());
                        int rt=ps.executeUpdate();
                        
                        if(rt>0){
                            
                            jf=new JFrame("INSERT RESULT");
                            jp=new JPanel();
                            l1=new JLabel("Successfully!");
                            jf.add(jp);
                            jp.add(l1);
                            jf.pack();
                            jf.setSize(400, 100);
                            jf.setLocationRelativeTo(null);
                            jf.setVisible(true);
                           
                        }
                                                                              
                    } catch (HeadlessException | SQLException ex) {
                        Logger.getLogger(insert.class.getName()).log(Level.SEVERE, null, ex);
                    }}
                else{
                    
                    jf2=new JFrame("INSERT RESULT");
                    jp2=new JPanel();
                    l2=new JLabel("Passwords aren't matched");
                    jf2.add(jp2);
                    jp2.add(l2);
                    jf2.pack();
                    jf2.setSize(400, 100);
                    jf2.setLocationRelativeTo(null);
                    jf2.setVisible(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(insert.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(insert.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login b=new login();
        b.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            insert a =new insert();
            a.setLocationRelativeTo(null);
            a.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C1;
    private javax.swing.JTextField E1;
    private javax.swing.JPasswordField P1;
    private javax.swing.JPasswordField Pa1;
    private javax.swing.JPasswordField Pp1;
    private javax.swing.JTextField U1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
