/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviebooking;

import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jenie
 */
public class Pay extends javax.swing.JFrame {
     JFrame jf;
     JPanel jp;
     JLabel l1;
     private String b1,b2,b3,b4,b5,b6,b7,b8,b9;
     
    /**
     * Creates new form Pay
     */
    public Pay(String a1,String a2,String a3,String a4,String a5,String a6,String a7,String a8,String a9) {
        this.b1=a1;this.b2=a2;this.b3=a3;this.b4=a4;this.b5=a5;this.b6=a6;this.b7=a7;this.b8=a8;this.b9=a9;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        u1 = new javax.swing.JTextField();
        p1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UserName:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PayPassword:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        jPanel1.add(u1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, -1));
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 180, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 153));
        jButton1.setText("Pay");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 180, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 300, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Moviename", "Moviedate", "Movietime", "Movietype", "Drink", "Seats", "Total", "Ordernumber", "Ordertime"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(120);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 1070, 140));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Sales status of BAG movie theater, don't miss the movie you like!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setText("Homepage");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 180, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/mo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        PreparedStatement pst=null;
        ResultSet rs=null;
        Connection con=null;
         try
        {
	//Class.forName("com.mysql.jdbc.Driver");		
        //Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306:/LoginDB?useSSL=false","root", "jing.,18x");
    
       con = DB.getConnection();
       String sql = "select * from bookinguser where UserName=? and Paypw1=?";
       
       pst=con.prepareStatement(sql);
       pst.setString(1,u1.getText());
       pst.setString(2,p1.getText());
      
      rs=pst.executeQuery();


       if(u1.getText().length()==0)
       {
      JOptionPane.showMessageDialog(this, "Empty User Name","Warning",JOptionPane.WARNING_MESSAGE);
       }
      else if(p1.getPassword().length==0)  
      {
      JOptionPane.showMessageDialog(this, "Empty Password","Warning",JOptionPane.WARNING_MESSAGE);
      }
       


      else if (rs.next())
       {
           
           jf=new JFrame("Pay");
                            jp=new JPanel();
                            l1=new JLabel("Finished!");
                            jf.add(jp);
                            jp.add(l1);
                            jf.pack();
                            jf.setSize(400, 100);
                            jf.setLocationRelativeTo(null);
                            jf.setVisible(true);
                            jButton1.setEnabled(false);
                            try {
                String str;
               str = "INSERT INTO information(moviename,moviedate,movietime,movietype,drink,seats,total,ordernumber,ordertime)VALUES (?,?,?,?,?,?,?,?,?)";
                
                PreparedStatement ps;
                
                PreparedStatement pt;
                con=DB.getConnection();
              
                
                 ps = con.prepareStatement(str);
                        ps.setString(1,b1);
                        ps.setString(2,b2);
                        ps.setString(3,b3);
                        ps.setString(4,b4);
                        ps.setString(5,b5);
                        ps.setString(6,b6);
                        ps.setString(7,b7);
                        ps.setString(8,b8);
                        ps.setString(9,b9);
                        int rt=ps.executeUpdate();
                       
        }    catch (SQLException ex) {
                 Logger.getLogger(Total.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IOException ex) {
                 Logger.getLogger(Total.class.getName()).log(Level.SEVERE, null, ex);
             }
           try{
       
         Statement statement =con.createStatement();
         String sql2=null;
         sql2="select * from information";
         ResultSet rs1 = statement.executeQuery(sql2);
         int i = 0, j = 0;
         while (rs1.next()) {
         jTable1.setValueAt(rs1.getString(1), i, j);
         jTable1.setValueAt(rs1.getString(2), i, j + 1);
         jTable1.setValueAt(rs1.getString(3), i, j + 2);
         jTable1.setValueAt(rs1.getString(4), i, j + 3);
         jTable1.setValueAt(rs1.getString(5), i, j + 4);
         jTable1.setValueAt(rs1.getString(6), i, j + 5);
         jTable1.setValueAt(rs1.getString(7), i, j + 6);
         jTable1.setValueAt(rs1.getString(8), i, j + 7);
         jTable1.setValueAt(rs1.getString(9), i, j + 8);
         i = i + 1;
         j = 0;
         }
         rs1.close();
         statement.close();
         } catch (SQLException ex) {
             Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
         }                 
           
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Incorrect User Name or Password","Error",JOptionPane.ERROR_MESSAGE);
       }
       }
       catch(HeadlessException | IOException | SQLException e)
       {
           JOptionPane.showMessageDialog(this, e);
           e.printStackTrace();
       }
         
         
         
         
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Homepage11 a =new Homepage11();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Pay m =new Pay("","","","","","","","","");
            m.setLocationRelativeTo(null);
            m.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField u1;
    // End of variables declaration//GEN-END:variables
}
