/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviebooking;

import javax.swing.JFrame;

/**
 *
 * @author jenie
 */
public class Upcoming extends javax.swing.JFrame {

    /**
     * Creates new form Upcoming
     */
    public Upcoming() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("HanziPen TC", 0, 24)); // NOI18N
        jLabel2.setText("Hit Movies");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("HanziPen TC", 3, 24)); // NOI18N
        jLabel1.setText("Upcoming Movies");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/DF8E8A10-D54C-434C-BE22-50E1488EB8EF.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 210, 330));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/8DC26B7E-79B3-4A4D-A4D1-13F22D75DDF6.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 210, 330));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/83FFD732-9B36-4DFF-9283-A4652AE52A45.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 210, 330));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/D97DC416-5437-4E6F-8217-76E98C314D49.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 210, 330));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/B7F71CBF-3BA9-444C-BF46-DC5BA300A0DD.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 210, 320));

        jButton4.setText("book now");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        jButton5.setText("book now");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));

        jButton6.setText("book now");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 780, -1, -1));

        jButton7.setText("book now");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 770, -1, -1));

        jButton8.setText("book now");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/D0DD891A002B3149A23A96ACD4F4202B.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 210, 320));

        jButton1.setText("book now");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 770, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviebooking/10A7DF55-47D0-4104-B425-73F12FC1956C.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 90, 210, 330));

        jButton2.setText("book now");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 420, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviebooking/4E6E74A5-DDEE-4B0D-AC92-56DEA031D12E.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 450, 210, 320));

        jButton3.setText("book now");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 770, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/timgOOBITL0N.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Homepage11 h1=new Homepage11();
        h1.show();
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
          pika2 a = new pika2("阿拉丁", "Aladdin", "2019/05/24", 134, 8.6, "79%", "Director:Guy Ritchie",
                "Actors:Will Smith, Mona Masoud, Naomi Scott, Marwan Kenzary",
                "<html><body>In the ancient Arab kingdom that is full of different region amorous feelings, kind-hearted poor<br>"
                        + " boy Aladdin and brave jasmine princess romantic encounter, below the help of the divine lamp demon <br>"
                        + "that can satisfy master 3 wishes, two people set foot on the magical adventure that seeks true <br>"
                        + "love and ego.......</body></html>"
        );
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         pika2 a = new pika2("X战警：黑凤凰", "X-Men: Dark Phoenix", "2019/06/06", 114, 0.0, "0%", "Director:Simon Kinberg",
                "Actors:James Mcavoy, Michael Fassbender, Jennifer Lawrence, Nicholas Holt, Sophie Turner, Jessica Chastain",
                "<html><body>The x-men will face their most powerful and feared enemy: one of their own, jean grey. During a space rescue mission, <br>"
                        + "jean is hit by a mysterious cosmic force and nearly dies. When she returned home, the force made her both incredibly powerful<br> "
                        + "and extremely unstable. During her struggle with internal energy, jean unleashed forces she could neither control nor comprehend.<br>"
                        + " As she continued to lose control, jean hurt her closest relatives. The move breaks the bonds that bind the x-men together.......</body></html>"
        );
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
            pika2 a = new pika2("音乐家", "The Composer", "2019/05/17", 104, 0.0, "0%", "Director:西尔扎提·亚合甫",
                "Actors:Hu Jun Yuan Quan",
                "<html><body>Xian xinghai, a people's musician, came to almaty during the great patriotic war of the Soviet union. In the last<br>"
                        + " years of his life, xian xinghai never forgot his original intention despite all the hardships. His heart was tied to <br>"
                        + "yan 'an and he inspired the Chinese people to fight against fascism with his music creation.......</body></html>"
        );
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
          pika2 a = new pika2("疾速求生", "John Wick: Chapter 2", "2019/02/17", 116, 7.9, "65%", "Director:Chad Stahelski",
                "Actors:Keanu Reeves, Ian McShane, Ruby Rose, Bridget Munna, Laurence Fishburne, Peter Sterman",
                "<html><body>John wake (keanu reeves) also reraises a healthy dog after a series of storms. Bent on retirement, John wake is once again <br>"
                        + "haunted by his previous career. His former employer is now being hunted down, trapped by his previous promise. John wake can only<br>"
                        + " fly to Rome to help him out. In the ancient city of Rome, John wake meets the world's most powerful killer, so he takes up a <br>"
                        + "gun to protect himself.......</body></html>"
        );
        a.setLocationRelativeTo(null);
        a.setExtendedState(JFrame.MAXIMIZED_BOTH);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Upcoming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Upcoming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Upcoming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Upcoming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Upcoming().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
